Added change that triggers this workflow for every pull request

diff --git a/.github/workflows/component_A2Q.yml b/.github/workflows/component_A2Q.yml
--- a/.github/workflows/component_A2Q.yml
+++ b/.github/workflows/component_A2Q.yml
@@ -24,6 +24,19 @@ jobs:
           echo "API_KEY: ${API_KEY:0:10}******" # Mask the API key for security
           echo "LICENSE_KEY: ${LICENSE_KEY:0:10}******" # Mask the license key for security
 
+
+      # Step 3: Test Connectivity to Metric Endpoint
+      - name: Test Connectivity to Metric Endpoint
+        run: |
+          echo "Testing connectivity to https://otlp.nr-data.net:4317/metric/v1..."
+          curl -v https://otlp.nr-data.net:4317/metric/v1 || echo "Failed to connect to Metric endpoint"
+
+      # Step 4: Test Connectivity to Events Endpoint
+      - name: Test Connectivity to Events Endpoint
+        run: |
+          echo "Testing connectivity to https://otlp.nr-data.net:4317/v1/accounts/events..."
+          curl -v https://otlp.nr-data.net:4317/v1/accounts/events || echo "Failed to connect to Events endpoint"
+
       - name: Test NRQL Query
         env:
           API_KEY: ${{ secrets.A2Q_API_KEY }} # New Relic API Key stored in GitHub Secrets
